#!/usr/bin/python

import argparse
parser = argparse.ArgumentParser()

parser.add_argument('files', type=str, nargs='+',
        help='names of files with data')

args = parser.parse_args()

print(args)
