#!/usr/bin/python3

import config

# parsing arguments
import argparse
parser = argparse.ArgumentParser()

parser.add_argument('files', type=str, nargs='+',
        help='names of files with data')

args = parser.parse_args()


# program itself
from core import output_filename, theoretical, search

from obspy import read

for datafile in vars(args)['files']:
    # reading file
    data = read(datafile)
    
    if config.PLOT_DATA_FROM_FILE: data.plot()

    if config.MODE == "theoretical":
        data = theoretical(data, datafile)
    elif config.MODE == "search":
        data = search(data, datafile)
    else:
        raise NotImplementedError

    if config.SAVE_RF:
        data.write(output_filename(datafile, prefix='rf_'), config.SAVE_FORMAT)
    if config.PLOT_RF:
        data.plot()
