#!/usr/bin/python3

# parsing arguments
import argparse
parser = argparse.ArgumentParser()

parser.add_argument('files', type=str, nargs='+',
        help='names of files with data')

args = parser.parse_args()


import matplotlib.pyplot as plt


for datafile in vars(args)['files']:
    f = open(datafile, 'r')
    data = f.read().split()
    f.close()

    plt.plot([float(x) for x in data])
    plt.show()
